baseurl = "https://shreyasportfolio.github.io"
title = "Shreyas Subramanian"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableRSS = true

[params]
  title = "Shreyas Subramanian"
  description = '<!--[-->I currently work for <a href="http://robust-analytics.com" target="_blank"> Robust Analytics</a> as the Director of Research. <!--]--><br />
                <!--[-->Do check out my recent work at <a href="http://projectshreyas.com" target="_blank">Project-S</a>.<!--]--><br />
                <!--[-->For a PDF copy of my <a href="https://shreyasportfolio.github.io/shreyassubramanian.pdf" target="_blank">R&Eacute;sum&Eacute;, click here</a>.<!--]-->'
  logo = "fa-fighter-jet"
  copyright = "Project-S"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "//facebook.com/w601sxs"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "//github.io/w601sxs"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "Shreyas Subramanian"
  description = '<!--[-->I currently work for <a href="http://robust-analytics.com" target="_blank"> Robust Analytics</a> as the Director of Research. <!--]--><br />
                <!--[-->Do check out my recent work at <a href="http://projectshreyas.com" target="_blank">Project-S</a>.<!--]--><br />
                <!--[-->For a PDF copy of my <a href="https://shreyasportfolio.github.io/shreyassubramanian.pdf" target="_blank">R&Eacute;sum&Eacute;, click here</a>.<!--]-->'
